#pragma once

// #define DIODE_DIRECTION COL2ROW

#define IGNORE_MOD_TAP_INTERRUPT
#define TAPPING_FORCE_HOLD
#define PERMISSIVE_HOLD
#define TAPPING_TERM 300

#define COMBO_COUNT 5

#define NO_AUTO_SHIFT_ALPHA
