COMMAND_ENABLE = no
CONSOLE_ENABLE = no
GRAVE_ESC_ENABLE = no 
MAGIC_ENABLE = no
MOUSEKEY_ENABLE = no
MOUSEKEY_ENABLE = no
RGBLIGHT_ENABLE = no
SPACE_CADET_ENABLE = no

TAP_DANCE_ENABLE = yes
COMBO_ENABLE = yes
